// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Security.Cryptography;
using System.Text;

namespace StoryboardTables
{
	public partial class CryptDecrypt : UIViewController
   {
  
      public CryptDecrypt(){}

      public override void ViewDidLoad()
      {
         base.ViewDidLoad();

         processcrypt.TouchUpInside+= delegate
         {
            this.Title="123";
         };
      }

	}

}
