// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace StoryboardTables
{
	public partial class HelpP : UIViewController
	{
		public HelpP (IntPtr handle) : base (handle)
		{
		}
	}
}
