// This file has been autogenerated from a class added in the UI designer.

using System;

using System.Drawing;
using MonoTouch.UIKit;

using MonoTouch.Foundation;
using System.IO;

namespace StoryboardTables
{
	public partial class imageViewCode : UIViewController
	{
      public string ImgUrl{ get; set;}
		public imageViewCode (IntPtr handle) : base (handle)
		{
		}

      UIScrollView scrollView;
      UIImageView imageView;


      #region -= constructors =-


      #endregion

      public override void ViewDidLoad ()
      {
         base.ViewDidLoad ();

         // set the background color of the view to white
         this.View.BackgroundColor = UIColor.White;

         this.Title = "Mecut Dosya";

         // create our scroll view
         scrollView = new UIScrollView (
            new RectangleF (0, 0, View.Frame.Width
               , View.Frame.Height - NavigationController.NavigationBar.Frame.Height));
         View.AddSubview (scrollView);





         string documentsPath = Environment.GetFolderPath(Environment.SpecialFolder.Personal);
         string localFilename = "original.jpg";
         string localPath = Path.Combine(documentsPath, localFilename);




         // create our image view
         imageView = new UIImageView (UIImage.FromFile (localPath));
         scrollView.ContentSize = imageView.Image.Size;
         scrollView.AddSubview (imageView);

         // set allow zooming
         scrollView.MaximumZoomScale = 3f;
         scrollView.MinimumZoomScale = .1f;        
         scrollView.ViewForZoomingInScrollView += (UIScrollView sv) => { return imageView; };

         // configure a double-tap gesture recognizer
         UITapGestureRecognizer doubletap = new UITapGestureRecognizer();
         doubletap.NumberOfTapsRequired = 2;
         doubletap.AddTarget (this, new MonoTouch.ObjCRuntime.Selector("DoubleTapSelector"));
         scrollView.AddGestureRecognizer(doubletap);
      }
      // implement the double-tap handler
      [MonoTouch.Foundation.Export("DoubleTapSelector")]
      public void OnDoubleTap (UIGestureRecognizer sender) {
         if (scrollView.ZoomScale >= 1)
            scrollView.SetZoomScale(0.25f, true);
         else 
            scrollView.SetZoomScale(2f, true);
      }
   }
}