// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Net.NetworkInformation;
using System.Net;

namespace StoryboardTables
{

	public partial class SecSide : UIViewController
	{

 
		public SecSide (IntPtr handle) : base (handle)
		{


		}
      public override void ViewDidLoad()
      {
         base.ViewDidLoad();
      }
	}
}
