// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Collections.Generic;
using System.Xml.Linq;
using System.IO;
using System.Linq;

namespace StoryboardTables
{

   public class TableSourceX : UITableViewSource 
   {
      string[] tableItems;
      string cellIdentifier = "TableCell";

      List<TaskX> tasks;
      public string namex;
      public string notesx;





  


      public TableSourceX(String[] items)
      {
         tableItems = items;

      }

      public override int RowsInSection(UITableView tableview, int section)
      {
         return tableItems.Length;
      }


      public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
      {

         UITableViewCell cell = tableView.DequeueReusableCell (cellIdentifier);
         // if there are no cells to reuse, create a new one
         if (cell == null)
            cell = new UITableViewCell (UITableViewCellStyle.Default, cellIdentifier);
         cell.TextLabel.Text = tableItems[indexPath.Row];
         return cell;
      }




   }
      
	public partial class SubeVerileriP : UIViewController
	{
      public string Sube {get;set;}

//      public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
//      {
//         base.PrepareForSegue(segue, sender);
//         if (segue.Identifier.Equals("gondery"))
//         {
//
//
//
//            var view = (XML2SQLX)segue.DestinationViewController;
//
//
//            Sube = this.bilgiF.Text;
//            view.Subebilgileri = Sube;
//
//
//
//         }
//
//      }


		public SubeVerileriP (IntPtr handle) : base (handle)
		{
		}
      UITableView view;

      public string Subex { get; set;}
      public override void ViewDidLoad()
      {
         base.ViewDidLoad();

         gosterX.TouchUpInside+= delegate
         {
            bilgiF.Text+= Subex;
         };

         gonderX.TouchUpInside+= delegate
         {
            this.PerformSegue("gondery",this);
         };


         string[] data  = { "haluk", "yılmaz" };
         tsource.Source = new TableSourceX(data);

         Add(tsource);
      }
	}
}
