// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace StoryboardTables
{
	public partial class Test2Data : UIViewController
	{
      public string  MyData { get; set; }

      public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
      {
         base.PrepareForSegue(segue, sender);
         if (segue.Identifier.Equals("testxx"))
         {




            var view = (WCFData)segue.DestinationViewController;

            view.MyData = "bilgilendiriciT.Text";



         }

      }



		public Test2Data (IntPtr handle) : base (handle)
		{
		}
      public override void ViewDidLoad()
      {
         base.ViewDidLoad();

         gostericiX.TouchUpInside+= delegate
         {
            this.PerformSegue("testxx", this);

         };
      
      }
	}
}
