// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace StoryboardTables
{
	public partial class WCFData : UIViewController
   {     
       public string  MyData { get; set; }

		public WCFData (IntPtr handle) : base (handle)
		{
		}

      public override void ViewDidLoad()
      {
         base.ViewDidLoad();


         gosterX.TouchUpInside+= delegate
         {
            new UIAlertView(MyData,"h",null,"OK",null).Show();
            userF.Text= MyData;
        
         
          };


      }
	}
}
