//// This file has been autogenerated from a class added in the UI designer.
//
//using System;
//
//using MonoTouch.Foundation;
//using MonoTouch.UIKit;
//using Mono.Data.Sqlite;
//using System.IO;
//
//namespace StoryboardTables
//{
//	public partial class TaskDetailViewControllerX : UITableViewController
//   { 
//      TaskX currentTask {get;set;}
//      public RootViewControllerX Delegate {get;set;}
//
//		public TaskDetailViewControllerX (IntPtr handle) : base (handle)
//		{
//		}
//
//      public override void ViewDidLoad ()
//      {
//         string SQLitePath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "IDBDBX.db3");
//
//         base.ViewDidLoad ();
//
//
//
//
//
//      SaveButton.TouchUpInside += (sender, e) => {
//         currentTask.Name = TitleText.Text;
//         currentTask.Notes = NotesText.Text;
//         currentTask.Done = DoneSwitch.On;
//
//
//         Delegate.SaveTask(currentTask);
//
//         UpdateData(SQLitePath);
//
//
//      };
//
//      DeleteButton.TouchUpInside += (sender, e) => {
//         Delegate.DeleteTask(currentTask);
//
//
//         DeleteData(SQLitePath);
//
//
//
//
//      };
//
//      
//      }
//
//
//
//
//
//   private void CreateData (string databaseFile)
//   {
//      try
//      {
//         if (!File.Exists (databaseFile))
//         {
//            return;
//         }
//         //end if
//
//         // Connect to database
//         using (SqliteConnection sqlCon = new SqliteConnection (String.Format ("Data Source = {0}", databaseFile)))
//         {
//            sqlCon.Open ();
//            using (SqliteCommand sqlCom = new SqliteCommand (sqlCon))
//            {
//               sqlCom.CommandText = "INSERT INTO Personel (UserName, Password) VALUES (@username, @password)";
//               sqlCom.Parameters.Add (new SqliteParameter ("@username",TitleText.Text ));
//               sqlCom.Parameters.Add (new SqliteParameter ("@password", NotesText.Text));
//               sqlCom.ExecuteNonQuery ();
//            }
//            //end using sqlCom
//
//            sqlCon.Close ();
//
//         }
//         //end using sqlCon
//
//
//      } catch (Exception ex)
//      {
//
//
//      }//end try catch
//
//
//   }//end void UpdateData
//
//
//
//
//
//      private void UpdateData (string databaseFile)
//      {
//
//         try
//         {
//
//            if (!File.Exists (databaseFile))
//            {
//
//               return;
//
//            }
//            //end if
//
//            // Connect to database
//            using (SqliteConnection sqlCon = new SqliteConnection (String.Format ("Data Source = {0}", databaseFile))) 
//            {
//
//               sqlCon.Open ();
//
//               if(idX.Text=="")
//               {
//                  using (SqliteCommand sqlCom = new SqliteCommand (sqlCon))
//                  {
//
//                     sqlCom.CommandText = "INSERT INTO Personel (UserName, Password) VALUES (@username, @password)";
//                     sqlCom.Parameters.Add (new SqliteParameter ("@username",TitleText.Text ));
//                     sqlCom.Parameters.Add (new SqliteParameter ("@password", NotesText.Text));
//
//
//
//
//                     sqlCom.ExecuteNonQuery ();
//
//                  }
//               }
//               if (idX.Text!=null)
//               {
//                  using (SqliteCommand sqlCom = new SqliteCommand (sqlCon)) 
//                  {
//
//                     sqlCom.CommandText = "UPDATE Personel SET UserName = @username , Password = @pass WHERE ID = @id";
//                     sqlCom.Parameters.Add (new SqliteParameter ("@username", TitleText.Text));
//                     sqlCom.Parameters.Add (new SqliteParameter ("@pass", NotesText.Text));
//
//                     sqlCom.Parameters.Add (new SqliteParameter ("@id",currentTask.Id));
//
//                     sqlCom.ExecuteNonQuery ();
//
//                  }
//                  //end using sqlCom
//
//                  sqlCon.Close ();
//
//               }
//            }
//
//            //end using sqlCon
//
//
//         } catch (Exception ex) 
//         {
//
//
//         }
//         //end try catch
//
//
//      }//end void UpdateData
//
//
//
//      private void DeleteData (string databaseFile)
//      {
//
//         try
//         {
//
//            if (!File.Exists (databaseFile))
//            {
//
//               return;
//
//            }
//            //end if
//
//            // Connect to database
//            using (SqliteConnection sqlCon = new SqliteConnection (String.Format ("Data Source = {0}", databaseFile)))
//            {
//
//               sqlCon.Open ();
//
//               using (SqliteCommand sqlCom = new SqliteCommand (sqlCon))
//               {
//                  sqlCom.CommandText = "DELETE FROM Personel WHERE ID = @id";
//                  sqlCom.Parameters.Add (new SqliteParameter ("@id",currentTask.Id));
//
//
//
//
//                  sqlCom.ExecuteNonQuery ();
//
//               }
//               //end using sqlCom
//
//               sqlCon.Close ();
//
//            }
//            //end using sqlCon
//
//            new UIAlertView("silindi","tamam",null,"OK",null);
//         } catch (Exception ex)
//         {
//
//            new UIAlertView("hata",ex.Message,null,"OK",null);
//
//         }//end try catch
//
//      }//end void InsertData
//
//
//      // when displaying, set-up the properties
//
//
//      // this will be called before the view is displayed 
//      public void SetTask (RootViewControllerX d, TaskX task) {
//         Delegate = d;
//         currentTask = task;
//      }
//
//   
//
//
//      // when displaying, set-up the properties
//      public override void ViewWillAppear (bool animated)
//      {
//         base.ViewWillAppear (animated);
//         TitleText.Text = currentTask.Name;
//         NotesText.Text = currentTask.Notes;
//         DoneSwitch.On = currentTask.Done;
//         idX.Text = TitleText.Text;
//
//
//      }
//
//      // this will be called before the view is displayed 
//     
//
//
//
//
//
//	}
//}
