// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.IO;
using System.Xml.Linq;
using System.Linq;

namespace StoryboardTables
{

   public class xmlData
   {

   }
   public partial class PRegist : UIViewController
   {

      public string  MyData { get; set; }



      public PRegist (IntPtr handle) : base (handle)
      {

      }

      public string Sube{get;set;}



      public static bool IsValidLogin(string user, string password)
      {
         string documentsPath = Environment.GetFolderPath(Environment.SpecialFolder.Personal);
         string localFilename = "Login.xml";
         string localPath = Path.Combine(documentsPath, localFilename);


         XDocument doc = XDocument.Load(localPath);

         return doc.Descendants("id")
               .Where(id => id.Attribute("UserName").Value == user 
                  && id.Attribute("Password").Value == password).Any();



      }

      public static string showIt(string user, string password)
      {
         string returnVal = "";
         string documentsPath = Environment.GetFolderPath(Environment.SpecialFolder.Personal);
         string localFilename = "Login.xml";
         string localPath = Path.Combine(documentsPath, localFilename);

         XDocument doc = XDocument.Load(localPath);



         var data = from x in  doc.Descendants("id")
            .Where(id => id.Attribute("UserName").Value == user
               && id.Attribute("Password").Value == password)
            select new { subeM = x.Element("Sube").Value};

         foreach (var yok in data)
            returnVal = yok.subeM.ToString();



         return returnVal;

      }


      public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
      {
         base.PrepareForSegue(segue, sender);
         if (segue.Identifier.Equals("bilgiAktar"))
         {

            var view = (XML2SQLX)segue.DestinationViewController;


            Sube = showIt(userT.Text, passT.Text);
            view.Subebilgileri = Sube;



         }

         else if (segue.Identifier.Equals("subeGonderbilgisi"))
         {
            var view = (XTEST)segue.DestinationViewController;


            Sube = showIt(userT.Text, passT.Text);
            view.SubeSistemi = Sube;




         }

      }





      public void goster()
      {
         string documentsPath = Environment.GetFolderPath(Environment.SpecialFolder.Personal);
         string localFilename = "Login.xml";
         string localPath = Path.Combine(documentsPath, localFilename);

         XDocument doc = XDocument.Load(localPath);


         var data = from x in doc.Descendants("id") where x.Element("Sube").Value == "Z"
                    select new {id = x.Element("Password").Value};

//         var data = from item in doc.Descendants("id")
//
//         select new
//         {
//            drink = item.Element("Sube"),
//            moneySpent = item.Element("UserName").Value,
//            zipCode = item.Element("Password").Value
//         };bilg
         foreach (var p in data)
            new UIAlertView(p.id.ToString() ,"",null,"OK",null).Show();
//
//     



      }

      public override void ViewDidLoad()
      {
         base.ViewDidLoad();




//         girisX.TouchUpInside+= delegate
//         {
//            // goster();
//            if(IsValidLogin(userT.Text,passT.Text))
//
//            {
//               tanitmamisiz.Text=  showIt(userT.Text,passT.Text);
//               showIt(userT.Text,passT.Text);
//               Sube= showIt(userT.Text,passT.Text);
//               this.PerformSegue("subeGoster", this);
//            }
//         };
//
//         baslatX.TouchDown+= delegate
//         {
//            if (IsValidLogin(userT.Text, passT.Text))
//            {
//               tanitmamisiz.Text = showIt(userT.Text, passT.Text);
//               showIt(userT.Text, passT.Text);
//               Sube = showIt(userT.Text, passT.Text);
//               this.PerformSegue("bilgiAktar", this);
//            }
//         };

         personelGirisi.TouchUpInside+= delegate
         {
            if (IsValidLogin(userT.Text, passT.Text))
            {
               tanitmamisiz.Text = showIt(userT.Text, passT.Text);
               showIt(userT.Text, passT.Text);
               Sube = showIt(userT.Text, passT.Text);

            this.PerformSegue("subeGonderbilgisi",this);
         
            }
         };

         guncelle.Clicked+= delegate {
            this.PerformSegue("segueGuncelle",this);
        };

      }
   }
}